src/java/co/com/pcshop/entities/Menu.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.com.pcshop.entities;

import java.io.Serializable;
import java.util.Collection;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 *
 * @author Usuario
 */
@Entity
@Table(name = "menu")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Menu.findAll", query = "SELECT m FROM Menu m")
    , @NamedQuery(name = "Menu.findByMenCodigo", query = "SELECT m FROM Menu m WHERE m.menCodigo = :menCodigo")
    , @NamedQuery(name = "Menu.findByMenNombre", query = "SELECT m FROM Menu m WHERE m.menNombre = :menNombre")
    , @NamedQuery(name = "Menu.findByMenuTipo", query = "SELECT m FROM Menu m WHERE m.menuTipo = :menuTipo")
    , @NamedQuery(name = "Menu.findByMenEstado", query = "SELECT m FROM Menu m WHERE m.menEstado = :menEstado")
    , @NamedQuery(name = "Menu.findByMenUrl", query = "SELECT m FROM Menu m WHERE m.menUrl = :menUrl")
    , @NamedQuery(name = "Menu.findByMenGeneral", query = "SELECT m FROM Menu m WHERE m.menuTipo = 'S'")
    , @NamedQuery(name = "Menu.findByMenUltimoId", query = "SELECT m FROM Menu m ORDER BY m.menCodigo DESC")})

public class Menu implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "men_codigo")
    private Integer menCodigo;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 20)
    @Column(name = "men_nombre")
    private String menNombre;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 1)
    @Column(name = "menu_tipo")
    private String menuTipo;
    @Basic(optional = false)
    @NotNull
    @Column(name = "men_estado")
    private boolean menEstado;
    @Size(max = 100)
    @Column(name = "men_url")
    private String menUrl;
    @OneToMany(mappedBy = "menCodigoSubmenu")
    private Collection<Menu> menuCollection;
    @JoinColumn(name = "men_codigo_submenu", referencedColumnName = "men_codigo")
    @ManyToOne
    private Menu menCodigoSubmenu;
    @JoinColumn(name = "menu_tipo_usuario", referencedColumnName = "tipusu_id")
    @ManyToOne
    private TipoUsuario menuTipoUsuario;

    public Menu() {
    }

    public Menu(Integer menCodigo) {
        this.menCodigo = menCodigo;
    }

    public Menu(Integer menCodigo, String menNombre, String menuTipo, boolean menEstado) {
        this.menCodigo = menCodigo;
        this.menNombre = menNombre;
        this.menuTipo = menuTipo;
        this.menEstado = menEstado;
    }

    public Integer getMenCodigo() {
        return menCodigo;
    }

    public void setMenCodigo(Integer menCodigo) {
        this.menCodigo = menCodigo;
    }

    public String getMenNombre() {
        return menNombre;
    }

    public void setMenNombre(String menNombre) {
        this.menNombre = menNombre;
    }

    public String getMenuTipo() {
        return menuTipo;
    }

    public void setMenuTipo(String menuTipo) {
        this.menuTipo = menuTipo;
    }

    public boolean getMenEstado() {
        return menEstado;
    }

    public void setMenEstado(boolean menEstado) {
        this.menEstado = menEstado;
    }

    public String getMenUrl() {
        return menUrl;
    }

    public void setMenUrl(String menUrl) {
        this.menUrl = menUrl;
    }

    @XmlTransient
    public Collection<Menu> getMenuCollection() {
        return menuCollection;
    }

    public void setMenuCollection(Collection<Menu> menuCollection) {
        this.menuCollection = menuCollection;
    }

    public Menu getMenCodigoSubmenu() {
        return menCodigoSubmenu;
    }

    public void setMenCodigoSubmenu(Menu menCodigoSubmenu) {
        this.menCodigoSubmenu = menCodigoSubmenu;
    }

    public TipoUsuario getMenuTipoUsuario() {
        return menuTipoUsuario;
    }

    public void setMenuTipoUsuario(TipoUsuario menuTipoUsuario) {
        this.menuTipoUsuario = menuTipoUsuario;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (menCodigo != null ? menCodigo.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Menu)) {
            return false;
        }
        Menu other = (Menu) object;
        if ((this.menCodigo == null && other.menCodigo != null) || (this.menCodigo != null && !this.menCodigo.equals(other.menCodigo))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "co.com.pcshop.entities.Menu[ menCodigo=" + menCodigo + " ]";
    }
    
}

src/java/co/com/pcshop/controller/MenuController.java
package co.com.pcshop.controller;

import co.com.pcshop.entities.Menu;
import co.com.pcshop.entities.TipoUsuario;
import co.com.pcshop.entities.Usuario;
import co.com.pcshop.facade.local.MenuFacadeLocal;
import co.com.pcshop.facade.local.TipoUsuarioFacadeLocal;
import java.io.Serializable;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import org.primefaces.model.menu.DefaultMenuItem;
import org.primefaces.model.menu.DefaultMenuModel;
import org.primefaces.model.menu.DefaultSubMenu;
import org.primefaces.model.menu.MenuModel;

@Named
@SessionScoped
public class MenuController implements Serializable {

    @EJB
    private MenuFacadeLocal menuEJB;
    @EJB
    private TipoUsuarioFacadeLocal tipousuarioEJB;

    private List<Menu> lista;
    private List<Menu> lista_menugeneral;

    private Menu menu;

    private int idtipousuario;
    private int idsubmenu;
    private String idmenu;

    List<Menu> listamenu = null;
    String mensaje = " ";

    private MenuModel model;

    public MenuModel getModel() {
        return model;
    }

    public void setModel(MenuModel model) {
        this.model = model;
    }

    public Menu getMenu() {
        return menu;
    }

    public void setMenu(Menu menu) {
        this.menu = menu;
    }

    public List<Menu> getLista() {
        return lista;
    }

    public void setLista(List<Menu> lista) {
        this.lista = lista;
    }

    public int getIdtipousuario() {
        return idtipousuario;
    }

    public void setIdtipousuario(int idtipousuario) {
        this.idtipousuario = idtipousuario;
    }

    public int getIdsubmenu() {
        return idsubmenu;
    }

    public void setIdsubmenu(int idsubmenu) {
        this.idsubmenu = idsubmenu;
    }

    public List<Menu> getListamenu() {
        if (listamenu == null) {
            listamenu = menuEJB.findAll();
        }
        listamenu = menuEJB.findAll();
        return listamenu;
    }

    public void setListamenu(List<Menu> listamenu) {
        this.listamenu = listamenu;
    }

    public List<Menu> getListamenugeneral() {
        if (lista_menugeneral == null) {
            lista_menugeneral = menuEJB.Menu_xTipo();
        }
        lista_menugeneral = menuEJB.Menu_xTipo();
        return lista_menugeneral;
    }

    public void setListamenugeneral(List<Menu> listamenu) {
        this.listamenu = listamenu;
    }

    public String getIdmenu() {
        return idmenu;
    }

    public void setIdmenu(String idmenu) {
        this.idmenu = idmenu;
    }

    @PostConstruct
    public void init() {
        menu = new Menu();
        this.ListarMenus();
        model = new DefaultMenuModel();
        this.EstablecerPermisos();
    }

    public void ListarMenus() {
        try {
            lista = menuEJB.findAll();
        } catch (Exception e) {

        }
    }

    public void EstablecerPermisos() {
        Usuario us = (Usuario) FacesContext.getCurrentInstance().getExternalContext().getSessionMap().get("usuario");
        //LLENA LOS MENUS QUE TIENEN SUBMENUS
        for (Menu m : lista) {
            //SI EL TIPO DE MENU = S Y EL MENU TIPO USUARIO = USUARIO TIPOUSUARIO
            if ((m.getMenuTipo()).equals("S") && m.getMenuTipoUsuario().equals(us.getUsuTipoUsuario())) {
                DefaultSubMenu firstSubmenu = new DefaultSubMenu(m.getMenNombre());
                for (Menu i : lista) {
                    Menu submenu = i.getMenCodigoSubmenu();
                    if (submenu != null) {
                        if (submenu.getMenCodigo() == m.getMenCodigo()) {
                            DefaultMenuItem item = new DefaultMenuItem(i.getMenNombre());
                            item.setUrl(i.getMenUrl());
                            firstSubmenu.addElement(item);
                        }
                    }
                }
//                for (Menu i : lista) {
//                    Menu submenu = i.getMenCodigoSubmenu();
//                    if (submenu != null) {
//                        if (submenu.getMenCodigo() == m.getMenCodigo()) {
//                            DefaultMenuItem item = new DefaultMenuItem(i.getMenNombre());
//                            item.setUrl(i.getMenUrl());
//                            firstSubmenu.addElement(item);
//                        }
//                    }
//                }
                model.addElement(firstSubmenu);
            } else {
                //LLENA SOLO LOS MENUS
                if (m.getMenCodigoSubmenu() == null && m.getMenuTipoUsuario().equals(us.getUsuTipoUsuario())) {
                    DefaultMenuItem item = new DefaultMenuItem(m.getMenNombre());
                    item.setUrl(m.getMenUrl());
                    model.addElement(item);
                }
            }
        }
    }

    public void guardar() {
        try {
            Menu menus = menuEJB.ultimoMenu();
            //SE OBTIENE EL ULTIMO id DE LOS MENUS
            int id_menu = menus.getMenCodigo();

            switch (idtipousuario) {
                case 0:
                    if (idsubmenu > 0) {
                        List<TipoUsuario> lista_tipousuarios = tipousuarioEJB.findAll();
                        for (TipoUsuario t : lista_tipousuarios) {
                            id_menu = id_menu + 1;
                            menu.setMenCodigo(id_menu);
                            menu.setMenuTipo(idmenu);
                            menu.setMenCodigoSubmenu(new Menu(idsubmenu));
                            menu.setMenuTipoUsuario(new TipoUsuario(t.getTipusuId()));
                            menuEJB.create(menu);
                            this.mensaje = "Registrado Correctamente";
                        }
                        menu = new Menu();
                    }else{
                        List<TipoUsuario> lista_tipousuarios = tipousuarioEJB.findAll();
                        for (TipoUsuario t : lista_tipousuarios) {
                            id_menu = id_menu + 1;
                            menu.setMenCodigo(id_menu);
                            menu.setMenuTipo(idmenu);
                            menu.setMenuTipoUsuario(new TipoUsuario(t.getTipusuId()));
                            menuEJB.create(menu);
                            this.mensaje = "Registrado Correctamente";
                        }
                        menu = new Menu();
                    }
                    
                    break;
                default:
                    if(idsubmenu>0){
                        menu.setMenuTipo(idmenu);
                        menu.setMenCodigoSubmenu(new Menu(idsubmenu));
                        menu.setMenuTipoUsuario(new TipoUsuario(idtipousuario));
                        menuEJB.create(menu);
                        menu = new Menu();
                        this.mensaje = "Registrado Correctamente";

                    }else{
                        menu.setMenuTipo(idmenu);
                        menu.setMenuTipoUsuario(new TipoUsuario(idtipousuario));
                        menuEJB.create(menu);
                        menu = new Menu();
                        this.mensaje = "Registrado Correctamente";
                    }
                    break;
            }
        } catch (Exception e) {
            this.mensaje = "ERROR :" + e.getMessage();
            menu = new Menu();
            e.printStackTrace();
        }
        FacesMessage msj = new FacesMessage(this.mensaje);
        FacesContext.getCurrentInstance().addMessage(null, msj);
        menu = new Menu();
        listamenu = menuEJB.findAll();
    }

//  
    public void cargarId(Menu m) {
        this.menu = m;
    }

    public void editar() {
        try {
            menu.setMenuTipo(idmenu);
            menu.setMenCodigoSubmenu(new Menu(idsubmenu));
            menu.setMenuTipoUsuario(new TipoUsuario(idtipousuario));
            menuEJB.edit(menu);
            this.mensaje = " editado Correctamente";
        } catch (Exception e) {
            this.mensaje = "ERROR :" + e.getMessage();
            e.printStackTrace();
        }
        FacesMessage msj = new FacesMessage(this.mensaje);
        FacesContext.getCurrentInstance().addMessage(null, msj);
        listamenu = menuEJB.findAll();
    }

    public void limpiar() {
        this.menu = new Menu();
    }

    public void eliminar(Menu m) {
        try {
            menuEJB.remove(m);
            this.mensaje = "eliminado Correctamente";
        } catch (Exception e) {
            this.mensaje = "ERROR :" + e.getMessage();
            e.printStackTrace();
        }
        FacesMessage msj = new FacesMessage(this.mensaje);
        FacesContext.getCurrentInstance().addMessage(null, msj);
        listamenu = menuEJB.findAll();
    }
}

web/Menu/listar.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
    <ui:composition template="/template.xhtml">
        <ui:define name="body">
            <h:body>
                <p:growl id="MSJ"/>

                <p:dialog widgetVar="tu"  showEffect="clip" resizable="false" header="Menu">
                    <p:ajax event="close" listener="#{menuController.limpiar()}" update=":da"/>
                    <h:form id="da">
                        <p:growl id="growle" showDetail="true" sticky="true" /> 
                        <p:panelGrid id="pgtu" columns="2" rendered="#{menuController.menu!=null}">
                            <p:outputLabel value="Nombre" for="idnombre" />
                            <p:inputText id="idnombre" value="#{menuController.menu.menNombre}" required="true" requiredMessage="Este campo es requerido"/>

                            <p:outputLabel for="idtipo" value="TIPO DE MENU" />
                            <p:selectOneMenu id="idtipo" value="#{menuController.idmenu}" required="true" requiredMessage="Este campo es requerido">
                                <f:selectItem itemLabel="SELECCIONAR" itemValue="" />
                                <f:selectItem itemLabel="MENU GENERAL" itemValue="S" />
                                <f:selectItem itemLabel="MENU FIJO" itemValue="F" />
                                <f:selectItem itemLabel="SUBMENU" itemValue="I" />
                            </p:selectOneMenu>

                            <p:outputLabel value="URL" for="idrul" />
                            <p:inputText id="idrul" value="#{menuController.menu.menUrl}" />

                            <p:outputLabel value="MENU GENERAL" for="idsubmenu" />
                            <p:selectOneMenu id="idsubmenu" value="#{menuController.idsubmenu}">
                                <f:selectItem itemLabel="SELECCIONAR" itemValue="" />
                                <f:selectItem itemLabel="NINGUNO" itemValue="" />
                                <f:selectItems value="#{menuController.listamenugeneral}" var="men" itemLabel="#{men.menNombre}" itemValue="#{men.menCodigo}"/>
                            </p:selectOneMenu>

                            <p:outputLabel value="Tipo Usuario" for="idtipousuario" />
                            <p:selectOneMenu id="idtipousuario" value="#{menuController.idtipousuario}">
                                <f:selectItem itemLabel="TODOS" itemValue="0" />
                                <f:selectItems value="#{tipoUsuarioController.listaTipousuario}" var="tipusu" itemLabel="#{tipusu.tipusuNombre}" itemValue="#{tipusu.tipusuId}"/>
                            </p:selectOneMenu>




                        </p:panelGrid>
                        <p:commandButton value="Guardar" actionListener="#{menuController.guardar()}" rendered="#{menuController.menu.menCodigo == null}" update=":Datos :MSJ" oncomplete="PF('tu').hide()"/>
                        <p:commandButton value="Editar" actionListener="#{menuController.editar()}" rendered="#{menuController.menu.menCodigo > 0}" update=":Datos :MSJ" oncomplete="PF('tu').hide()"/>
                        <p:commandButton value="Cancelar" oncomplete="PF('tu').hide()"/>
                    </h:form>
                </p:dialog>
                <h:form id="Datos"> 
                    <p:spacer width="10"/>
                    <p:panel header="Menus">
                        <p:commandLink  oncomplete="PF('tu').show()" title="Nuevo Menu">
                            <p:graphicImage height="40" width="40" library="images" name="nuevo.png"/>
                        </p:commandLink>
                        <p:spacer width="20"/>
                        <h:commandLink title="Exportar PDF">
                            <h:graphicImage url="/resources/images/pdf.png" height="30" width="30"/>
                            <p:dataExporter type="pdf" target="idUsuarios" fileName="Usuarios"/>
                        </h:commandLink>
                        <p:spacer width="20"/>
                        <h:commandLink title="Exportar XLS">
                            <h:graphicImage url="/resources/images/excel.png" height="30" width="30"/>
                            <p:dataExporter type="xls" target="idUsuarios" fileName="Usuarios"/>
                        </h:commandLink>
                        <p:dataTable id="idUsuarios" var="item" value="#{menuController.listamenu}" paginator="true" rows="10"
                                     paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                                     currentPageReportTemplate="{startRecord}-{endRecord} de {totalRecords} Resultados"
                                     rowsPerPageTemplate="5,10,15">
                            <p:column headerText="Codigo">
                                <h:outputText value="#{item.menCodigo}" />
                            </p:column>
                            <p:column headerText="Nombre">
                                <h:outputText value="#{item.menNombre}" />
                            </p:column>
                            <p:column headerText="URL">
                                <h:outputText value="#{item.menUrl}" />
                            </p:column>
                            <p:column headerText="Tipo">
                                <center>
                                    <h:outputText value="#{item.menuTipo}" />
                                </center>
                            </p:column>
                            <p:column headerText="Tipo Usuario">
                                <h:outputText value="#{item.menuTipoUsuario.tipusuNombre}" />
                            </p:column>
                            <p:column headerText="Sub Menu">
                                <h:outputText value="#{item.menCodigoSubmenu.menNombre}" />
                            </p:column>
                            <p:column headerText="Estado">
                                <h:outputText value="#{item.menEstado}" />
                            </p:column>
                            <p:column headerText="Acciones">
                                <center>
                                    <p:commandLink  id="Editar" actionListener="#{menuController.cargarId(item)}" update=":da" oncomplete="PF('tu').show()">
                                        <p:graphicImage height="30" width="30" library="images" name="editar.png"/>
                                    </p:commandLink>
                                    <p:spacer width="10"/>
                                    <p:commandLink  id="Eliminar" actionListener="#{menuController.eliminar(item)}" update=":Datos :MSJ">
                                        <p:graphicImage height="30" width="30" library="images" name="eliminar.png"/>
                                    </p:commandLink>
                                </center>
                            </p:column>
                        </p:dataTable>
                    </p:panel>
                </h:form>
            </h:body>
        </ui:define>
    </ui:composition>
</html>