src/java/co/com/pcshop/entities/Referencia.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.com.pcshop.entities;

import java.io.Serializable;
import java.util.Collection;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 *
 * @author Usuario
 */
@Entity
@Table(name = "referencia")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Referencia.findAll", query = "SELECT r FROM Referencia r")
    , @NamedQuery(name = "Referencia.findByRefId", query = "SELECT r FROM Referencia r WHERE r.refId = :refId")
    , @NamedQuery(name = "Referencia.findByRefFoto", query = "SELECT r FROM Referencia r WHERE r.refFoto = :refFoto")
    , @NamedQuery(name = "Referencia.findByRefNombre", query = "SELECT r FROM Referencia r WHERE r.refNombre = :refNombre")
    , @NamedQuery(name = "Referencia.findByRefNota", query = "SELECT r FROM Referencia r WHERE r.refNota = :refNota")
    , @NamedQuery(name = "Referencia.findByRefCantidadStock", query = "SELECT r FROM Referencia r WHERE r.refCantidadStock = :refCantidadStock")})
public class Referencia implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "ref_id")
    private Integer refId;
    @Size(max = 100)
    @Column(name = "ref_foto")
    private String refFoto;
    @Size(max = 40)
    @Column(name = "ref_nombre")
    private String refNombre;
    @Size(max = 255)
    @Column(name = "ref_nota")
    private String refNota;
    @Basic(optional = false)
    @NotNull
    @Column(name = "ref_cantidad_stock")
    private int refCantidadStock;
    @OneToMany(mappedBy = "comReferencia")
    private Collection<Compra> compraCollection;
    @OneToMany(mappedBy = "venReferencia")
    private Collection<Venta> ventaCollection;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "referencia")
    private Collection<ReferenciaSede> referenciaSedeCollection;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "referencia")
    private Collection<ReferenciaListaPrecio> referenciaListaPrecioCollection;
    @JoinColumn(name = "ref_linea", referencedColumnName = "lin_id")
    @ManyToOne
    private Linea refLinea;
    @JoinColumn(name = "ref_marca", referencedColumnName = "mar_id")
    @ManyToOne
    private Marca refMarca;

    public Referencia() {
    }

    public Referencia(Integer refId) {
        this.refId = refId;
    }

    public Referencia(Integer refId, int refCantidadStock) {
        this.refId = refId;
        this.refCantidadStock = refCantidadStock;
    }

    public Integer getRefId() {
        return refId;
    }

    public void setRefId(Integer refId) {
        this.refId = refId;
    }

    public String getRefFoto() {
        return refFoto;
    }

    public void setRefFoto(String refFoto) {
        this.refFoto = refFoto;
    }

    public String getRefNombre() {
        return refNombre;
    }

    public void setRefNombre(String refNombre) {
        this.refNombre = refNombre;
    }

    public String getRefNota() {
        return refNota;
    }

    public void setRefNota(String refNota) {
        this.refNota = refNota;
    }

    public int getRefCantidadStock() {
        return refCantidadStock;
    }

    public void setRefCantidadStock(int refCantidadStock) {
        this.refCantidadStock = refCantidadStock;
    }

    @XmlTransient
    public Collection<Compra> getCompraCollection() {
        return compraCollection;
    }

    public void setCompraCollection(Collection<Compra> compraCollection) {
        this.compraCollection = compraCollection;
    }

    @XmlTransient
    public Collection<Venta> getVentaCollection() {
        return ventaCollection;
    }

    public void setVentaCollection(Collection<Venta> ventaCollection) {
        this.ventaCollection = ventaCollection;
    }

    @XmlTransient
    public Collection<ReferenciaSede> getReferenciaSedeCollection() {
        return referenciaSedeCollection;
    }

    public void setReferenciaSedeCollection(Collection<ReferenciaSede> referenciaSedeCollection) {
        this.referenciaSedeCollection = referenciaSedeCollection;
    }

    @XmlTransient
    public Collection<ReferenciaListaPrecio> getReferenciaListaPrecioCollection() {
        return referenciaListaPrecioCollection;
    }

    public void setReferenciaListaPrecioCollection(Collection<ReferenciaListaPrecio> referenciaListaPrecioCollection) {
        this.referenciaListaPrecioCollection = referenciaListaPrecioCollection;
    }

    public Linea getRefLinea() {
        return refLinea;
    }

    public void setRefLinea(Linea refLinea) {
        this.refLinea = refLinea;
    }

    public Marca getRefMarca() {
        return refMarca;
    }

    public void setRefMarca(Marca refMarca) {
        this.refMarca = refMarca;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (refId != null ? refId.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Referencia)) {
            return false;
        }
        Referencia other = (Referencia) object;
        if ((this.refId == null && other.refId != null) || (this.refId != null && !this.refId.equals(other.refId))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "co.com.pcshop.entities.Referencia[ refId=" + refId + " ]";
    }
    
}

src/java/co/com/pcshop/controller/ReferenciaController.java
package co.com.pcshop.controller;

import co.com.pcshop.entities.Linea;
import co.com.pcshop.entities.Marca;
import co.com.pcshop.entities.Referencia;
import co.com.pcshop.entities.Sede;
import co.com.pcshop.facade.local.ReferenciaFacadeLocal;
import co.com.pcshop.util.Constantes;
import co.com.pcshop.util.UtilPath;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.Serializable;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Named;
import org.primefaces.model.UploadedFile;
import org.primefaces.model.chart.PieChartModel;


@Named
@ViewScoped
public class ReferenciaController implements Serializable { 
    String mensaje="";
    
    @EJB
    private ReferenciaFacadeLocal referenciaEJB;
    
    private Referencia referencia;
    private Linea linea;
    private Marca marca;
    
    private int idlinea;
    private int idmarca;
    
    List<Referencia> listareferencia = null;
    
    private UploadedFile file;
    String destination;
    String ImageName = "";
    
    @PostConstruct
    public void init(){
        referencia = new Referencia();
    }

    public Referencia getReferencia() {
        return referencia;
    }

    public void setReferencia(Referencia referencia) {
        this.referencia = referencia;
    }
    
    public List<Referencia> getListareferencia() {

        if (listareferencia == null) {
            listareferencia = referenciaEJB.findAll();
        }
        listareferencia = referenciaEJB.findAll();
        return listareferencia;
    }

    public void setListareferencia(List<Referencia> listareferencia) {
        this.listareferencia = listareferencia;
    }

    public UploadedFile getFile() {
        return file;
    }

    public void setFile(UploadedFile file) {
        this.file = file;
    }

    public Linea getLinea() {
        return linea;
    }

    public void setLinea(Linea linea) {
        this.linea = linea;
    }

    public Marca getMarca() {
        return marca;
    }

    public void setMarca(Marca marca) {
        this.marca = marca;
    }

    public int getIdlinea() {
        return idlinea;
    }

    public void setIdlinea(int idlinea) {
        this.idlinea = idlinea;
    }

    public int getIdmarca() {
        return idmarca;
    }

    public void setIdmarca(int idmarca) {
        this.idmarca = idmarca;
    }
    
    
    
    public void guardar() {
        try{
            if (upload()) {
                referencia.setRefFoto(ImageName);
                referencia.setRefLinea(new Linea(idlinea));
                referencia.setRefMarca(new Marca(idmarca));
                referenciaEJB.create(referencia);
                referencia = new Referencia();
                mensaje="Se guardo la Referencia Satisfactoriamente!";
                destination = "";
                System.out.println("destination = " + destination);
            }
        }catch (Exception e){
            mensaje="Error: "+e.getMessage();
            e.printStackTrace();
        }
        FacesMessage msj = new FacesMessage(mensaje);
        FacesContext.getCurrentInstance().addMessage(null,msj);
    }
    
    public void cargaId (Referencia referencia){
        this.referencia = referencia;
    }
    
    public void editar(){
        try{
            if (upload()) {
                referencia.setRefFoto(ImageName);
                referencia.setRefLinea(new Linea(idlinea));
                referencia.setRefMarca(new Marca(idmarca));
                referenciaEJB.edit(referencia);
                mensaje="Se modifico la Referencia Satisfactoriamente!";
                this.referencia = new Referencia();
                destination = "";
                System.out.println("destination = " + destination);
            }else{
                referencia.setRefLinea(new Linea(idlinea));
                referencia.setRefMarca(new Marca(idmarca));
                referenciaEJB.edit(referencia);
                mensaje = "Se modifico la Referencia Satisfactoriamente!";
                referencia = new Referencia();
                destination = "";
                System.out.println("destination = " + destination);
            }
        }catch (Exception e){
            mensaje="Error: "+e.getMessage();
            e.printStackTrace();
        }
        FacesMessage msj = new FacesMessage(mensaje);
        FacesContext.getCurrentInstance().addMessage(null,msj);
    }
    
    public Boolean upload() {
        try {
            System.out.println("uload = ");
            destination = Constantes.URL_REFERENCIAS;
            System.out.println("UPLOAD destination = " + destination);
            File folder = new File(UtilPath.getPath() + destination);
            if (!folder.exists()) {
                folder.mkdirs();
            }
            copyFile(getFile().getFileName(), getFile().getInputstream());
            if("".equals(getFile().getFileName())){
                return false;
            }
            return true;
        } catch (IOException e) {
            return false;
        }
    }

    public void copyFile(String fileName, InputStream in) {
        try {
            System.out.println("copyfile = ");
            ImageName=fileName;
            ExternalContext ec = FacesContext.getCurrentInstance().getExternalContext();
            String realPath = UtilPath.getPathDefinida(ec.getRealPath("/"));
            destination = destination + Constantes.SEPARADOR + fileName;
            System.out.println("COPYFILE destination = " + destination);
            OutputStream out = new FileOutputStream(new File(realPath + destination));

            int read = 0;
            byte[] bytes = new byte[1024];

            while ((read = in.read(bytes)) != -1) {
                out.write(bytes, 0, read);
            }
            in.close();
            out.flush();
            out.close();

        } catch (IOException e) {
            System.out.println(e.getMessage());
            //JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("error_cargar_doc"));
        }
    }
    
    public void eliminar(Referencia u){
        try{
            referenciaEJB.remove(u);
            referencia = new Referencia();
            referencia.setRefLinea(new Linea());
            referencia.setRefMarca(new Marca());
            mensaje="Se elimino la Referencia Satisfactoriamente!";
        }catch (Exception e){
            mensaje="Error: "+e.getMessage();
            e.printStackTrace();
        }
        FacesMessage msj = new FacesMessage(this.mensaje);
        FacesContext.getCurrentInstance().addMessage(null,msj);
    }
    
    public void limpiar(){
        referencia = new Referencia();
        referencia.setRefLinea(new Linea());
        referencia.setRefMarca(new Marca());
    }
    
    
}

src/java/co/com/pcshop/controller/ReferenciaSedeController.java
package co.com.pcshop.controller;

import co.com.pcshop.entities.Referencia;
import co.com.pcshop.entities.ReferenciaSede;
import co.com.pcshop.entities.Sede;
import co.com.pcshop.facade.local.ReferenciaSedeFacadeLocal;
import java.io.Serializable;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

@ManagedBean
@SessionScoped
public class ReferenciaSedeController implements Serializable {

    @EJB
    private ReferenciaSedeFacadeLocal refsedEJB;
    
    //SE CREAN LOS OBJECTOS
    private ReferenciaSede refsed;
    private Referencia referencia;
    private Sede sede;
    
    List<ReferenciaSede> listarefsed = null;
    
    String mensaje = " ";

    public ReferenciaSede getReflispre() {
        return refsed;
    }

    public void setReflispre(ReferenciaSede refsed) {
        this.refsed = refsed;
    }

    public Referencia getReferencia() {
        return referencia;
    }

    public void setReferencia(Referencia referencia) {
        this.referencia = referencia;
    }

    public Sede getSede() {
        return sede;
    }

    public void setSede(Sede sede) {
        this.sede = sede;
    }

    
    
    public List<ReferenciaSede> getListarefsed() {

        if (listarefsed == null) {
            listarefsed = refsedEJB.findAll();
        }
        listarefsed = refsedEJB.findAll();
        return listarefsed;
    }

    public void setListarefsed(List<ReferenciaSede> listarefsed) {
        this.listarefsed = listarefsed;
    }
    
    @PostConstruct
    public void init() {
        refsed = new ReferenciaSede();//genera una instancia al objeto
    }
    
    public void cargarId(ReferenciaSede p) {
        this.refsed = p;
    }

    public void limpiar() {
        this.refsed = new ReferenciaSede();
    }
}

web/Referencia/AsignarPrecios.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
    <ui:composition template="/template.xhtml">
        <ui:define name="body">
            <h:body>
                <p:growl id="MSJ"/>
                <p:dialog widgetVar="tu"  showEffect="clip" resizable="false" header="Referencia Lista Precio">
                    <p:ajax event="close" listener="#{referenciaListaPrecioController.limpiar()}" update=":da"/>
                    <h:form id="da">
                        <p:growl id="growle" showDetail="true" sticky="true" /> 
                        <p:panelGrid id="pgtu" columns="2" rendered="#{referenciaListaPrecioController.reflispre!=null}">
                            <p:outputLabel value="Referencia" for="idreferencia" />
                            <p:inputText id="idreferencia" value="#{referenciaListaPrecioController.reflispre.referencia.refNombre}" readonly="true"/>
                            <p:outputLabel value="Lista Precio" for="idlistaprecio" />
                            <p:inputText id="idlistaprecio" value="#{referenciaListaPrecioController.reflispre.listaPrecio.lispreNombre}" readonly="true"/>
                            <p:outputLabel value="Valor" for="idvalor" />
                            <p:inputText id="idvalor" value="#{referenciaListaPrecioController.reflispre.reflispreValor}" required="true"/>
                            <p:outputLabel value="Descuento" for="iddescuento" />
                            <p:inputText id="iddescuento" value="#{referenciaListaPrecioController.reflispre.reflispreDescuento}" required="true"/>
                        </p:panelGrid>
                        <p:commandButton value="Editar" actionListener="#{referenciaListaPrecioController.editar()}" update=":Datos :MSJ" oncomplete="PF('tu').hide()" ajax="false"/>
                        <p:commandButton value="Cancelar" oncomplete="PF('tu').hide()"/>
                    </h:form>
                </p:dialog>
                <h:form id="Datos"> 
                    <p:spacer width="20"/>
                    <p:panel header="Referencia Lista Precio">
                        <h:commandLink title="Exportar PDF">
                            <h:graphicImage url="/resources/images/pdf.png" height="30" width="30"/>
                            <p:dataExporter type="pdf" target="idReferencias" fileName="pdfReferencias"/>
                        </h:commandLink>
                            <p:spacer width="20"/>
                        <h:commandLink title="Exportar XLS">
                            <h:graphicImage url="/resources/images/excel.png" height="30" width="30"/>
                            <p:dataExporter type="xls" target="idReferencias" fileName="excelReferencias"/>
                        </h:commandLink>
                        <p:dataTable id="idReferencias" var="item" value="#{referenciaListaPrecioController.listareflispre}" paginator="true" rows="10"
                                     paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                                     currentPageReportTemplate="{startRecord}-{endRecord} de {totalRecords} Resultados"
                                     rowsPerPageTemplate="5,10,15">
                            <p:column headerText="Nombre">
                                <h:outputText value="#{item.referencia.refNombre}" />
                            </p:column>
                            <p:column headerText="Foto">
                                <center>
                                <p:graphicImage  height="100" width="100" value="/resources/images/referencias/#{item.referencia.refFoto}" />
                                </center>
                            </p:column>
                            <p:column headerText="Lista Precio">
                                <h:outputText value="#{item.listaPrecio.lispreNombre}" />
                            </p:column>
                            <p:column headerText="Valor">
                                <center>
                                    <h:outputText value="#{item.reflispreValor}" />
                                </center>
                            </p:column>
                            <p:column headerText="Descuento">
                                <center>
                                    <h:outputText value="#{item.reflispreDescuento}" />
                                </center>
                            </p:column>
                            <p:column headerText="Acciones">
                                <center>
                                <p:commandLink  id="Editar" actionListener="#{referenciaListaPrecioController.cargarId(item)}" update=":da" oncomplete="PF('tu').show()">
                                    <p:graphicImage height="25" width="25" library="images" name="editar.png"/>
                                </p:commandLink>
                                </center>
                            </p:column>
                        </p:dataTable>
                    </p:panel>
                </h:form>
            </h:body>
        </ui:define>
    </ui:composition>
</html>

web/Referencia/ReferenciaSede.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
    <ui:composition template="/template.xhtml">
        <ui:define name="body">
            <h:body>
                <h:form id="Datos"> 
                    <p:spacer width="20"/>
                    <p:panel header="Referencias por Sedes">
                        <h:commandLink title="Exportar PDF">
                            <h:graphicImage url="/resources/images/pdf.png" height="30" width="30"/>
                            <p:dataExporter type="pdf" target="idReferenciasSedes" fileName="pdfReferencias"/>
                        </h:commandLink>
                        <p:spacer width="20"/>
                        <h:commandLink title="Exportar XLS">
                            <h:graphicImage url="/resources/images/excel.png" height="30" width="30"/>
                            <p:dataExporter type="xls" target="idReferenciasSedes" fileName="excelReferencias"/>
                        </h:commandLink>
                        <p:dataTable id="idReferenciasSedes" var="item" value="#{referenciaSedeController.listarefsed}" paginator="true" rows="10"
                                     widgetVar="itemTable"
                                     emptyMessage="No hay criterio para esta búsqueda"

                                     paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                                     currentPageReportTemplate="{startRecord}-{endRecord} de {totalRecords} Resultados"
                                     rowsPerPageTemplate="5,10,15">
                             <f:facet name="header" >
                                <p:outputPanel style="position:relative;left:-282px;">
                                    <h:outputText value="Buscar Todos"/>
                                    <p:inputText id="globalFilter" onkeyup="PF('itemTable').filter()" style="width: 292px;" placeholder="Buscar por: Nombre - Sede - Marca"/>
                                </p:outputPanel>
                            </f:facet>
                            <p:column headerText="STOCK">
                                <h:outputText value="#{item.refsedCantidad}" />
                            </p:column>
                            <p:column headerText="Nombre" filterBy="#{item.referencia.refNombre}" filterStyle="display:none">
                                <h:outputText value="#{item.referencia.refNombre}" />
                            </p:column>
                            <p:column headerText="Foto">
                                <center>
                                    <p:graphicImage  height="100" width="100" value="/resources/images/referencias/#{item.referencia.refFoto}" />
                                </center>
                            </p:column>
                            <p:column headerText="Marca" filterBy="#{item.referencia.refMarca.marFoto}" filterStyle="display:none">
                                <center>
                                    <p:graphicImage  height="45" width="45" value="/resources/images/marcas/#{item.referencia.refMarca.marFoto}" />
                                </center>
                            </p:column>
                            <p:column headerText="Sede" filterBy="#{item.sede.sedNombre}" filterStyle="display:none">
                                <h:outputText value="#{item.sede.sedNombre}" />
                            </p:column>
                            <p:column headerText="Foto">
                                <center>
                                    <p:graphicImage  height="100" width="100" value="/resources/images/sedes/#{item.sede.sedFoto}" />
                                </center>
                            </p:column>
                            <p:column headerText="Direccion">
                                <h:outputText value="#{item.sede.sedDireccion}" />
                            </p:column>
                            <p:column headerText="Telefono">
                                <h:outputText value="#{item.sede.sedTelefono}" />
                            </p:column>
                        </p:dataTable>
                    </p:panel>
                </h:form>
            </h:body>
        </ui:define>
    </ui:composition>
</html>

web/Referencia/ReferenciaSede_Compras.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
    <ui:composition template="/template.xhtml">
        <ui:define name="body">
            <h:body>
                <p:growl id="MSJ"/>

                <p:dialog widgetVar="tu"  showEffect="clip" resizable="false" header="Comprar Referencia">
                    <p:ajax event="close" listener="#{ventaController_Compra.limpiar()}" update=":da"/>
                    <h:form id="da">
                        <p:growl id="growle" showDetail="true" sticky="true" /> 
                        <p:panelGrid id="pgtu" columns="2" rendered="#{ventaController_Compra.venta!=null}">
                            <p:outputLabel value="Sede" for="idsede" />
                            <p:selectOneMenu id="idsede" value="#{ventaController_Compra.idsede}">
                                <f:selectItems value="#{sedeController.listaSede}" var="sed" itemLabel="#{sed.sedNombre}" itemValue="#{sed.sedId}"/>
                            </p:selectOneMenu>

                            <p:outputLabel value="Referencia" for="idreferencia" />
                            <p:selectOneMenu id="idreferencia" value="#{ventaController_Compra.idreferencia}">
                                <f:selectItems value="#{referenciaController.listareferencia}" var="ref" itemLabel="#{ref.refNombre}" itemValue="#{ref.refId}"/>
                            </p:selectOneMenu>                    

                            <p:outputLabel value="Cantidad" for="idcantidad" />
                            <p:inputText id="idcantidad" value="#{ventaController_Compra.cantidad}" required="true" requiredMessage="Este campo es requerido"/>

                        </p:panelGrid>
                        <p:commandButton value="Guardar" actionListener="#{ventaController_Compra.guardar()}" rendered="#{ventaController_Compra.venta.venId == null}" update=":Datos :MSJ" oncomplete="PF('tu').hide()"/>
                        <p:commandButton value="Cancelar" oncomplete="PF('tu').hide()"/>
                    </h:form>
                </p:dialog>



                <h:form id="Datos"> 
                    <p:spacer width="20"/>
                    <p:panel header="Referencias por Sedes">
                        <p:commandLink  title="Comprar Referencia" id="Comprar" actionListener="#{referenciaController.cargaId(item)}" update=":da" oncomplete="PF('tu').show()">
                            <p:graphicImage height="30" width="30" library="images" name="icon-comprar.png"/>
                        </p:commandLink>
                        <p:spacer width="20"/>

                        <p:dataTable id="idReferenciasSedes" var="item" value="#{referenciaSedeController.listarefsed}" paginator="true" rows="10"
                                     widgetVar="itemTable"
                                     emptyMessage="No hay criterio para esta búsqueda"
                                     paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                                     currentPageReportTemplate="{startRecord}-{endRecord} de {totalRecords} Resultados"
                                     rowsPerPageTemplate="5,10,15">
                            <f:facet name="header" >
                                <p:outputPanel style="position:relative;left:-282px;">
                                    <h:outputText value="Buscar Todos"/>
                                    <p:inputText id="globalFilter" onkeyup="PF('itemTable').filter()" style="width: 292px;" placeholder="Buscar por: Nombre - Sede"/>
                                </p:outputPanel>
                            </f:facet>
                            <p:column headerText="STOCK">
                                <h:outputText value="#{item.refsedCantidad}" />
                            </p:column>
                            <p:column headerText="Nombre" filterBy="#{item.referencia.refNombre}" filterStyle="display:none">
                                <h:outputText value="#{item.referencia.refNombre}" />
                            </p:column>
                            
                            <p:column headerText="Foto">
                                <center>
                                    <p:graphicImage  height="100" width="100" value="/resources/images/referencias/#{item.referencia.refFoto}" />
                                </center>
                            </p:column>
                            <p:column headerText="Marca">
                                <center>
                                    <p:graphicImage  height="45" width="45" value="/resources/images/marcas/#{item.referencia.refMarca.marFoto}" />
                                </center>
                            </p:column>
                            <p:column headerText="Sede" filterBy="#{item.sede.sedNombre}" filterStyle="display:none">
                                <h:outputText value="#{item.sede.sedNombre}" />
                            </p:column>
                            <p:column headerText="Foto">
                                <center>
                                    <p:graphicImage  height="100" width="100" value="/resources/images/sedes/#{item.sede.sedFoto}" />
                                </center>
                            </p:column>
                            <p:column headerText="Direccion">
                                <h:outputText value="#{item.sede.sedDireccion}" />
                            </p:column>
                            <p:column headerText="Telefono">
                                <h:outputText value="#{item.sede.sedTelefono}" />
                            </p:column>
                        </p:dataTable>
                    </p:panel>
                </h:form>
            </h:body>
        </ui:define>
    </ui:composition>
</html>